### ISSUE TITLE
"moved" urls (which redirect) get 404 "Not Found" in GHI, work fine in git or github-web

### ISSUE THREAD

**Issue by smemsh** [stephencelis/ghi#210]
`ghi` seems to break when the github URL has changed since checkout:

    $ git config --get remote.origin.url
    https://github.com/hifi/raspbian-ua-netinst

    $ curl -LI --stderr - https://github.com/hifi/raspbian-ua-netinst |
      grep -e ^Location -e ^Status
    Status: 301 Moved Permanently
    Location: https://github.com/debian-pi/raspbian-ua-netinst
    Status: 200 OK

I tried 0.9.3 (gem install) and also trunk as of now (d89b5abbf0ab5428a2459cbfdd3b074ddc23373d) shown below:

    $ ./ghi list -- hifi/raspbian-ua-netinst | wc -l
    Not Found
    1

    $ ./ghi list -- debian-pi/raspbian-ua-netinst | wc -l
    17

only the canonicalized URL works.  Since this is a 304 it should probably be followed by `ghi`

**Comment by AlexChesters** [comment]
Hi @smemsh,

Thanks for reporting this! I've recently become a contributor to `ghi` and have experienced the same issue. Although rather than getting a 404 I actually get `Moved Permanently` in the output.

**Comment by AlexChesters** [comment]
This issue has been fixed in 63987afff3a340be816b39e2bef850d50271506e

**Comment by smemsh** [comment]
@AlexChesters with master branch (which appears to
include your commit 63987af) I still get the same issue
with the repository mentioned in my initial issue submission,
but this time there is no error, just an empty list.  In
particular, a `ghi list` with the old url shows no issues
(has empty output), but with the new url, a full issue list
is shown.

Just try these two commands:
```
./ghi list -- hifi/raspbian-ua-netinst
./ghi list -- debian-pi/raspbian-ua-netinst
```
to see the difference.  The former is the old, the
latter is the new.  If you go to the url in a browser
(http://github.com/hifi/raspbian-ua-netinst) you will
end up at the new url after it follows the redirect.

I would say this issue is not fixed, since ghi isn't
following the redirect.

(aside: incidentally, your patch embeds tabs in the
source files, but surrounding code is space-expanded)

**Comment by AlexChesters** [comment]
@smemsh strange, it worked for me on one of my repos but not for the one you've shown... I'll have a look into this now

**Comment by AlexChesters** [comment]
@smemsh made some progress. [This line](https://github.com/stephencelis/ghi/blob/master/lib/ghi/formatting.rb#L186) is at fault. When commented out it works fine...

**Comment by AlexChesters** [comment]
@smemsh I've managed to fix this :smile: will get a patch out now.

**Comment by AlexChesters** [comment]
@smemsh This has been fixed in [1.0.3](https://github.com/stephencelis/ghi/releases/tag/1.0.3), thanks for reporting this!

The release is already available from `rubygems` now and will be available from `brew` as soon as [this pull request](https://github.com/Homebrew/homebrew/pull/45157) is merged.

Thanks again :smile:

**Comment by smemsh** [comment]
confirmed, works now with bfe6349.  thanks!

**Comment by AlexChesters** [comment]
@smemsh no worries :-)
